name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service

    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        if: ${{ github.ref == '/refs/head/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
# above was found in https://github.com/docker/login-action to find secret from github and login to docker
# so that on next line we can push the build to docker


      - name: Build and Publish Docker Image
        if: ${{ github.ref == '/refs/head/main' }}
        run: |
           ./mvnw spring-boot:build-image -DskipTests
           echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
           docker push $DOCKER_IMAGE_NAME

